# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: SQNS Merge Check

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [12.x, 14.x, 16.x]
        mongo-version: [6.0.10]

    services:
      mongodb-${{ github.run_id }}-${{ github.run_number }}-${{ matrix.cpu }}:
        image: mongo:${{ matrix.mongo-version }}
        options: >-
          --health-cmd "echo 'db.runCommand("ping").ok' | mongosh --quiet"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
          --name mongo_container_${{ github.run_id }}_${{ github.run_number }}_${{ matrix.node-version }}

    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
    - run: npm ci
    - run: node_modules/eslint/bin/eslint.js  --ext .ts src
    - run: node_modules/eslint/bin/eslint.js  --ext .ts typings
    - run: node_modules/tslint/bin/tslint -p ./ -c src/tslint.json
    - run: node_modules/typescript/bin/tsc -p ./
    - run: rm -r dist
    - name: coverage
      run: |
        node_modules/.bin/nyc node_modules/.bin/mocha src/setup.ts '**/*.spec.ts'
        node_modules/.bin/nyc report --reporter=text-lcov > coverage1.lcov
      env:
        DEBUG: no
        TEST_DB: mongoDB
        MONGODB_URI: mongodb://mongodb-${{ github.run_id }}-${{ github.run_number }}-${{ matrix.node-version }}/sqns
    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@v3
      with:
        token: ${{ secrets.CODECOV_TOKEN }}
